/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TrasFormers.java
 *
 * Created on May 6, 2011, 5:40:17 PM
 */

package transformers;

import java.util.Locale;

/**
 *
 * @author ^O^
 */
public class TrasFormersGUI extends javax.swing.JFrame {

    /** Creates new form TrasFormers */
    public TrasFormersGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tranfromers number.");

        jTextField1.setAutoscrolls(false);
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel1.setText("Insert number=>>");

        jLabel2.setText("Select input base.");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("8");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("10");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("16");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton1)))
        );

        jLabel3.setText("  Select output base.");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("2");

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("8");

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setText("10");

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setText("16");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jRadioButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(6, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton8)))
        );

        jLabel4.setText("Answer.");

        jButton1.setText("Process");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel2)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            String NumHex,NumOct,NumBin,NumDec;
            NumOct=jTextField1.getText();
            NumHex=jTextField1.getText();
            NumBin=jTextField1.getText();
            NumDec=jTextField1.getText();
            ChkBitB ChkBin=new ChkBitB();
            ChkBitH ChkHex=new ChkBitH();
            ChkBitO ChkOct=new ChkBitO();
            ChkBitD ChkDec=new ChkBitD();
            BToD BinToDec=new BToD();
            BToH BinToHex=new BToH();
            BToO BinToOct=new BToO();
            DToB DecToBin=new DToB();
            HToB HexToBin=new HToB();
            OToB OctToBin=new OToB();

            if(((jRadioButton1.isSelected()==true)&&(jRadioButton5.isSelected()==true))||((jRadioButton2.isSelected()==true)&&(jRadioButton6.isSelected()==true))||((jRadioButton3.isSelected()==true)&&(jRadioButton7.isSelected()==true))||((jRadioButton4.isSelected()==true)&&(jRadioButton8.isSelected()==true))){
                    if(((jRadioButton1.isSelected()==true)&&(jRadioButton5.isSelected()==true))){
                        ChkBin.setInput(NumBin);
                        if(ChkBin.getOutput()==1)
                            jLabel5.setText(NumBin);                    
                        if(ChkBin.getOutput()==0)
                            jLabel5.setText("Insert '0' or '1'. ");
                    }
                    else if(((jRadioButton2.isSelected()==true)&&(jRadioButton6.isSelected()==true))){
                        ChkOct.setInput(NumOct);
                        if(ChkOct.getOutput()==1)                       
                            jLabel5.setText(NumOct);                    
                        if(ChkOct.getOutput()==0)
                            jLabel5.setText("Insert '0' to '7'. ");
                    }
                    else if(((jRadioButton3.isSelected()==true)&&(jRadioButton7.isSelected()==true))){
                        ChkDec.setInput(NumDec);
                        if(ChkDec.getOutput()==1)
                            jLabel5.setText(NumDec);                   
                        if(ChkDec.getOutput()==0)
                            jLabel5.setText("Insert '0' to '9'. ");
                    }
                    else {
                        ChkHex.setInput(NumHex);
                        if(ChkHex.getOutput()==1)
                            jLabel5.setText(NumHex=NumHex.toUpperCase());
                        if(ChkHex.getOutput()==0)
                            jLabel5.setText("Insert '0' to 'F'. ");
                    }
            }
            else if(((jRadioButton1.isSelected() == true) && (jRadioButton6.isSelected() == true))){
                    ChkBin.setInput(NumBin);
                    if(ChkBin.getOutput()==1){
                        BinToOct.setBin(NumBin);
                        jLabel5.setText(BinToOct.getShowBiOct());
                    }
                    if(ChkBin.getOutput()==0)
                        jLabel5.setText("Insert '0' or '1'. ");
            }
            else if(((jRadioButton1.isSelected()==true)&&(jRadioButton7.isSelected()==true))){
                    ChkBin.setInput(NumBin);
                    if(ChkBin.getOutput()==1){
                        BinToDec.setBin(NumBin);
                        jLabel5.setText(String.valueOf(BinToDec.getShowBiDec()));
                    }
                    if(ChkBin.getOutput()==0)
                        jLabel5.setText("Insert '0' or '1'. ");
            }
            else if(((jRadioButton1.isSelected()==true)&&(jRadioButton8.isSelected()==true))){
                    ChkBin.setInput(NumBin);
                    if(ChkBin.getOutput()==1){
                        BinToHex.setBin(NumBin);
                        jLabel5.setText(BinToHex.getShowBiHex());
                    }
                    if(ChkBin.getOutput()==0)
                        jLabel5.setText("Insert '0' or '1'. ");
            }
            else if(((jRadioButton2.isSelected()==true)&&(jRadioButton5.isSelected()==true))){
                    ChkOct.setInput(NumOct);
                    if(ChkOct.getOutput()==1){
                        OctToBin.setOct(NumOct);
                        jLabel5.setText(OctToBin.getShowOctBin());
                    }
                    if(ChkOct.getOutput()==0)
                        jLabel5.setText("Insert '0' to '7'. ");
            }
            else if(((jRadioButton2.isSelected()==true)&&(jRadioButton7.isSelected()==true))){
                    ChkOct.setInput(NumOct);
                    if(ChkOct.getOutput()==1){
                        OctToBin.setOct(NumOct);
                        BinToDec.setBin(OctToBin.getShowOctBin());
                        jLabel5.setText(String.valueOf(BinToDec.getShowBiDec()));
                    }
                    if(ChkOct.getOutput()==0)
                        jLabel5.setText("Insert '0' to '7'. ");
            }
            else if(((jRadioButton2.isSelected()==true)&&(jRadioButton8.isSelected()==true))){
                    ChkOct.setInput(NumOct);
                    if(ChkOct.getOutput()==1){
                        OctToBin.setOct(NumOct);
                        BinToHex.setBin(OctToBin.getShowOctBin());
                        jLabel5.setText(BinToHex.getShowBiHex());
                    }
                    if(ChkOct.getOutput()==0)
                        jLabel5.setText("Insert '0' to '7'. ");
            }
            else if(((jRadioButton3.isSelected()==true)&&(jRadioButton5.isSelected()==true))){
                    ChkDec.setInput(NumDec);
                    if(ChkDec.getOutput()==1){
                        int Nd=Integer.parseInt(NumDec);
                        DecToBin.setDec(Nd);
                        jLabel5.setText(DecToBin.getShowDecBin());
                    }
                    if(ChkDec.getOutput()==0)
                        jLabel5.setText("Insert '0' to '9'. ");
            }
            else if(((jRadioButton3.isSelected()==true)&&(jRadioButton6.isSelected()==true))){
                    ChkDec.setInput(NumDec);
                    if(ChkDec.getOutput()==1){
                        int Nd=Integer.parseInt(NumDec);
                        DecToBin.setDec(Nd);
                        BinToOct.setBin(DecToBin.getShowDecBin());
                        jLabel5.setText(BinToOct.getShowBiOct());
                    }
                    if(ChkDec.getOutput()==0)
                        jLabel5.setText("Insert '0' to '9'. ");
            }
            else if(((jRadioButton3.isSelected()==true)&&(jRadioButton8.isSelected()==true))){
                    ChkDec.setInput(NumDec);
                    if(ChkDec.getOutput()==1){
                        int Nd=Integer.parseInt(NumDec);
                        DecToBin.setDec(Nd);
                        BinToHex.setBin(DecToBin.getShowDecBin());
                        jLabel5.setText(BinToHex.getShowBiHex());
                    }
                    if(ChkDec.getOutput()==0)
                        jLabel5.setText("Insert '0' to '9'. ");
            }
            else if(((jRadioButton4.isSelected()==true)&&(jRadioButton5.isSelected()==true))){
                    ChkHex.setInput(NumHex);
                    if(ChkHex.getOutput()==1){
                        HexToBin.setHex(NumHex);
                        jLabel5.setText(HexToBin.getShowHexBin());
                    }
                    if(ChkHex.getOutput()==0)
                        jLabel5.setText("Insert '0' to 'F'. ");
            }
            else if(((jRadioButton4.isSelected()==true)&&(jRadioButton6.isSelected()==true))){
                    ChkHex.setInput(NumHex);
                    if(ChkHex.getOutput()==1){
                        HexToBin.setHex(NumHex);
                        BinToOct.setBin(HexToBin.getShowHexBin());
                        jLabel5.setText(BinToOct.getShowBiOct());
                    }
                    if(ChkHex.getOutput()==0)
                        jLabel5.setText("Insert '0' to 'F'. ");
            }
            else{
                    ChkHex.setInput(NumHex);
                    if(ChkHex.getOutput()==1){
                        HexToBin.setHex(NumHex);
                        BinToDec.setBin(HexToBin.getShowHexBin());
                        jLabel5.setText(String.valueOf(BinToDec.getShowBiDec()));
                    }
                    if(ChkHex.getOutput()==0)
                        jLabel5.setText("Insert '0' to 'F'. ");
            }                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrasFormersGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
